""" create comments table 

Revision ID: 77dfbda0c6cd
Revises: c6f5a13a781f
Create Date: 2024-04-17 00:06:02.762432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77dfbda0c6cd'
down_revision = 'c6f5a13a781f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_comment_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('body', sa.String(length=555), nullable=False),
    sa.ForeignKeyConstraint(['game_comment_id'], ['games.game_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Comments')
    # ### end Alembic commands ###
