"""create users table

Revision ID: ba5b018331ca
Revises: 77dfbda0c6cd
Create Date: 2024-04-17 12:57:16.566510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5b018331ca'
down_revision = '77dfbda0c6cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_comment_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('body', sa.String(length=555), nullable=False),
    sa.ForeignKeyConstraint(['game_comment_id'], ['games.game_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('game_comment_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=50), nullable=True),
    sa.Column('body', sa.VARCHAR(length=555), nullable=False),
    sa.ForeignKeyConstraint(['game_comment_id'], ['games.game_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('comments')
    op.drop_table('users')
    # ### end Alembic commands ###
